In [8]:
import pandas as pd
import numpy as np
import json

#These files were constructed from the individual agency data pulled from the FBI's Crime Data Explorer, and then aggregated to the state level.
df_NM = pd.read_csv('../DATA/PROCESSED_CRIME_DATA/NM_arrests_2024.csv') 
df_CO = pd.read_csv('../DATA/PROCESSED_CRIME_DATA/CO_arrests_2024.csv')

In [9]:
df_NM

,ori,counties,is_nibrs,latitude,longitude,state_abbr,state_name,agency_name,agency_type_name,nibrs_start_date,county_name,Arrests_2024,Population_2024
0,NM0130500,LEA,False,32.795687,-103.413271,NM,New Mexico,Tatum Police Department,City,NaN,LEA,0,673
1,NM0130000,LEA,True,32.935955,-103.341995,NM,New Mexico,Lea County Sheriff's Office,County,10/1/2020,LEA,514,16133
2,NM0130100,LEA,True,32.795687,-103.413271,NM,New Mexico,Eunice Police Department,City,1/1/2021,LEA,21,2904
3,NM0130200,LEA,True,32.702976,-103.136190,NM,New Mexico,Hobbs Police Department,City,1/1/2020,LEA,2072,38972
4,NM0130300,LEA,True,32.795687,-103.413271,NM,New Mexico,Jal Police Department,City,1/1/2021,LEA,1,2075
...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,NMDI08300,NOT SPECIFIED,True,NaN,NaN,NM,New Mexico,Zia Pueblo,Tribal,1/1/2021,NOT SPECIFIED,44,0
131,NMNSP0000,UNMAPPED COUNTY,True,35.513731,-105.966439,NM,New Mexico,New Mexico State Police,State Police,4/1/2023,UNMAPPED COUNTY,4,0
132,NM0230600,"BERNALILLO, SANDOVAL",True,35.268604,-106.634796,NM,New Mexico,Rio Rancho Police Department,City,12/1/2020,"BERNALILLO, SANDOVAL",2130,112817
133,NM0261200,"BERNALILLO, SANTA FE",True,35.513731,-105.966439,NM,New Mexico,Edgewood Police Department,City,2/1/2021,"BERNALILLO, SANTA FE",136,6113
134,NM0210100,"RIO ARRIBA, SANTA FE",False,36.509669,-106.693983,NM,New Mexico,Espanola Police Department,City,NaN,"RIO ARRIBA, SANTA FE",0,10400

In [10]:
df_CO

,ori,counties,is_nibrs,latitude,longitude,state_abbr,state_name,agency_name,agency_type_name,nibrs_start_date,county_name,Arrests_2024,Population_2024
0,CO0050700,BACA,True,37.306678,-102.537765,CO,Colorado,Walsh Police Department,City,10/1/2004,BACA,0,504
1,CO0050000,BACA,True,37.412470,-102.614260,CO,Colorado,Baca County Sheriff's Office,County,1/1/1997,BACA,0,1543
2,CO0050100,BACA,True,37.406647,-102.616520,CO,Colorado,Springfield Police Department,City,1/1/2003,BACA,46,1280
3,CO0060000,BENT,True,37.931891,-103.077584,CO,Colorado,Bent County Sheriff's Office,County,1/1/1997,BENT,129,5800
4,CO0330000,LAKE,True,39.205341,-106.350079,CO,Colorado,Lake County Sheriff's Office,County,1/1/1997,LAKE,125,4780
...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,CO0010500,"ADAMS, JEFFERSON",True,39.863120,-105.050415,CO,Colorado,Westminster Police Department,City,1/1/1997,"ADAMS, JEFFERSON",3467,114310
253,CO0030600,"ARAPAHOE, JEFFERSON",True,39.619427,-105.046050,CO,Colorado,Bow Mar Police Department,City,1/1/1997,"ARAPAHOE, JEFFERSON",0,814
254,CO0550100,"RIO GRANDE, SAGUACHE",True,38.031651,-106.234666,CO,Colorado,Center Police Department,City,1/1/1997,"RIO GRANDE, SAGUACHE",60,1922
255,CO0010100,"ADAMS, ARAPAHOE, DOUGLAS",True,39.709550,-104.814930,CO,Colorado,Aurora Police Department,City,1/1/1985,"ADAMS, ARAPAHOE, DOUGLAS",10432,397852
256,CO0030200,"ARAPAHOE, DOUGLAS, JEFFERSON",True,39.616898,-105.014540,CO,Colorado,Littleton Police Department,City,1/1/2011,"ARAPAHOE, DOUGLAS, JEFFERSON",631,44076

In [11]:
import matplotlib.pyplot as plt

df_plot_NM = df_NM.dropna(subset=['latitude', 'longitude'])
df_plot_CO = df_CO.dropna(subset=['latitude', 'longitude'])

In [12]:
import plotly.express as px

fig = px.scatter_mapbox(
    df_NM,
    lat="latitude",
    lon="longitude",
    size="Arrests_2024",          # bubble size
    color="Arrests_2024",         # optional color scaling
    hover_name="agency_name",
    hover_data=["Arrests_2024", "Population_2024"],
    size_max=40,
    zoom=6
)

fig.update_layout(
    mapbox_style="carto-positron",  # clean background
    margin={"r":0,"t":0,"l":0,"b":0}
)

plt.savefig("../FIGURES/Figure_1.png")

fig.show()

C:\Users\laura\AppData\Local\Temp\ipykernel_13072\3704193787.py:3: DeprecationWarning: *scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  fig = px.scatter_mapbox(

In [13]:
fig = px.scatter_mapbox(
    df_CO,
    lat="latitude",
    lon="longitude",
    size="Arrests_2024",          # bubble size
    color="Arrests_2024",         # optional color scaling
    hover_name="agency_name",
    hover_data=["Arrests_2024", "Population_2024"],
    size_max=40,
    zoom=6
)

fig.update_layout(
    mapbox_style="carto-positron",  # clean background
    margin={"r":0,"t":0,"l":0,"b":0}
)

plt.savefig("../FIGURES/Figure_2.png")

fig.show()

C:\Users\laura\AppData\Local\Temp\ipykernel_13072\2122538065.py:1: DeprecationWarning:

*scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/

In [15]:
with open('../DATA/RAW_CRIME_DATA/response_1771464984839.json', 'r') as f:
    data = json.load(f)

actuals = data["actuals"]["United States Arrests"]
population = data["populations"]["population"]["United States"]
rates = data["rates"]["United States Arrests"]

df = pd.DataFrame({
    "Month": actuals.keys(),
    "Arrests": actuals.values()
})

df["Population"] = df["Month"].map(population)
df["Arrest_Rate_per_100k"] = df["Month"].map(rates)

df

      Month  Arrests  Population  Arrest_Rate_per_100k
0   01-2024   554749   343551384                168.55
1   02-2024   570322   343551384                173.43
2   03-2024   605709   343551384                184.40
3   04-2024   594357   343551384                180.83
4   05-2024   625809   343551384                190.69
5   06-2024   592814   343551384                180.25
6   07-2024   617936   343551384                187.96
7   08-2024   628102   343551384                191.06
8   09-2024   591524   343551384                180.07
9   10-2024   594551   343551384                180.97
10  11-2024   552474   343551384                168.52
11  12-2024   541570   343551384                165.13

In [16]:
df['Arrests'].sum()

np.int64(7069917)

In [17]:
df_US = pd.read_csv('../DATA/PROCESSED_CRIME_DATA/Estimated_Arrests_US_2024.csv', header=None)

df_US

                                                 0        1
0                                            Total  7522824
1             Murder and nonnegligent manslaughter    10522
2                                             Rape    18784
3                                          Robbery    64804
4                               Aggravated assault   325313
5                                         Burglary   110925
6                                    Larceny-theft   725109
7                              Motor vehicle theft    66191
8                                            Arson     8429
9                                    Violent crime   419423
10                                  Property crime   910654
11                                  Other assaults  1018216
12                      Forgery and counterfeiting    36445
13                                           Fraud    85643
14                                    Embezzlement     8811
15  Stolen property; buying, receiving, possessing    70427
16                                       Vandalism   162380
17             Weapons; carrying, possessing, etc.   163091
18            Prostitution and commercialized vice    12811
19     Sex offenses (except rape and prostitution)    20202
20                           Drug abuse violations   822488
21                                        Gambling     2036
22        Offenses against the family and children    47175
23                     Driving under the influence   804926
24                                     Liquor laws    96890
25                                     Drunkenness     6339
26                              Disorderly conduct   271642
27                                        Vagrancy    24471
28                              All other offenses  2531936
29                                       Suspicion        0
30             Curfew and loitering law violations     6818

In [ ]:
df_US.iloc[1:30, 1].sum()

np.int64(8846083)

In [18]:
df_CO_arrestee = pd.read_csv("../DATA/RAW_CRIME_DATA/CO-2024/NIBRS_ARRESTEE.csv")

df_CO_arrestee.head()

,data_year,arrestee_id,incident_id,arrestee_seq_num,arrest_date,arrest_type_id,multiple_indicator,offense_code,age_id,age_num,sex_code,race_id,ethnicity_id,resident_code,under_18_disposition_code,clearance_ind,age_range_low_num,age_range_high_num
0,2024,60255601,197328785,1,1/3/2024,3,C,90F,26,23,M,10,10,R,NaN,NaN,23,NaN
1,2024,57502324,188853124,1,1/3/2024,3,C,13B,28,25,M,10,10,R,NaN,NaN,25,NaN
2,2024,56479851,185588235,1,1/8/2024,3,C,280,25,22,M,10,10,N,NaN,NaN,22,NaN
3,2024,56479857,185588257,1,1/9/2024,3,C,13B,69,66,F,10,10,N,NaN,NaN,66,NaN
4,2024,56479860,185588268,1,1/11/2024,2,C,13B,26,23,M,10,20,N,NaN,NaN,23,NaN

In [19]:
df_CO_incident = pd.read_csv("../DATA/RAW_CRIME_DATA/CO-2024/NIBRS_incident.csv")

df_CO_incident.head()

,data_year,agency_id,incident_id,nibrs_month_id,cargo_theft_flag,submission_date,incident_date,report_date_flag,incident_hour,cleared_except_id,cleared_except_date,incident_status,data_home,orig_format,did
0,2024,1826,197328785,44883648,f,2024-09-16 18:21:50.042,2024-01-03,f,0.0,6,NaN,ACCEPTED,NaN,X,269230654
1,2024,1868,185588198,44732274,f,2024-02-07 17:01:05.134,2024-01-02,f,7.0,6,NaN,ACCEPTED,NaN,X,231103153
2,2024,1868,185588201,44732274,f,2024-02-07 17:01:05.855,2024-01-03,f,1.0,6,NaN,ACCEPTED,NaN,X,231103161
3,2024,1868,188853124,44732274,f,2024-04-04 07:01:10.962,2024-01-02,f,20.0,6,NaN,ACCEPTED,NaN,X,241640711
4,2024,1868,185588211,44732274,f,2024-02-07 17:01:08.954,2024-01-03,f,20.0,6,NaN,ACCEPTED,NaN,X,231103191

In [20]:
df_CO_offense_type = pd.read_csv("../DATA/RAW_CRIME_DATA/CO-2024/NIBRS_OFFENSE_TYPE.csv")

df_CO_offense_type

,offense_code,offense_name,crime_against,ct_flag,hc_flag,hc_code,offense_category_name,offense_group
0,09C,Justifiable Homicide,Person,f,f,,Homicide Offenses,A
1,09A,Murder and Nonnegligent Manslaughter,Person,f,t,01,Homicide Offenses,A
2,09B,Negligent Manslaughter,Person,f,t,,Homicide Offenses,A
3,11A,Rape,Person,f,t,02,Sex Offenses,A
4,11B,Sodomy,Person,f,t,02,Sex Offenses,A
...,...,...,...,...,...,...,...,...
81,23D,Theft From Building,Property,t,t,,Larceny/Theft Offenses,A
82,23E,Theft From Coin-Operated Machine or Device,Property,f,t,,Larceny/Theft Offenses,A
83,23F,Theft From Motor Vehicle,Property,t,t,,Larceny/Theft Offenses,A
84,23G,Theft of Motor Vehicle Parts or Accessories,Property,f,t,,Larceny/Theft Offenses,A
85,23H,All Other Larceny,Property,t,t,,Larceny/Theft Offenses,A

In [21]:
df_CO_offense_type['offense_group'].value_counts()

offense_group
A    72
B    13
      1
Name: count, dtype: int64

In [22]:
df_CO_ethnicity = pd.read_csv("../DATA/RAW_CRIME_DATA/CO-2024/NIBRS_ETHNICITY.csv")

df_CO_ethnicity

   ethnicity_id ethnicity_code          ethnicity_name
0            10              H      Hispanic or Latino
1            20              N  Not Hispanic or Latino
2            30              M                Multiple
3            40              U                 Unknown
4            50              X           Not Specified

In [23]:
df_NM_arrestee = pd.read_csv("../DATA/RAW_CRIME_DATA/NM-2024/NIBRS_ARRESTEE.csv")

df_NM_arrestee.head()

,data_year,arrestee_id,incident_id,arrestee_seq_num,arrest_date,arrest_type_id,multiple_indicator,offense_code,age_id,age_num,sex_code,race_id,ethnicity_id,resident_code,under_18_disposition_code,clearance_ind,age_range_low_num,age_range_high_num
0,2024,56333576,185132381,1,2024-01-01,2,N,23C,27,24,M,10,10,R,NaN,NaN,24.0,NaN
1,2024,56333577,185132385,1,2024-01-01,3,N,35B,33,30,F,10,10,R,NaN,NaN,30.0,NaN
2,2024,56333578,185132391,1,2024-01-02,2,N,290,28,25,F,10,10,R,NaN,NaN,25.0,NaN
3,2024,56333579,185132397,1,2024-01-02,3,N,13B,55,52,M,10,20,R,NaN,NaN,52.0,NaN
4,2024,56333580,185132401,1,2024-01-02,3,N,280,46,43,M,10,10,R,NaN,NaN,43.0,NaN

In [24]:
df_NM_arrestee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30598 entries, 0 to 30597
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   data_year                  30598 non-null  int64
 1   arrestee_id                30598 non-null  int64
 2   incident_id                30598 non-null  int64
 3   arrestee_seq_num           30598 non-null  int64
 4   arrest_date                30598 non-null  object
 5   arrest_type_id             30598 non-null  int64
 6   multiple_indicator         30598 non-null  object
 7   offense_code               30598 non-null  object
 8   age_id                     30598 non-null  int64
 9   age_num                    30598 non-null  int64
 10  sex_code                   30598 non-null  object
 11  race_id                    30598 non-null  int64
 12  ethnicity_id               30598 non-null  int64
 13  resident_code              26285 non-null  object
 14  under_18_disposition_code  1885 non-null   object
 15  clearance_ind              0 non-null      float64
 16  age_range_low_num          30590 non-null  float64
 17  age_range_high_num         45 non-null     float64
dtypes: float64(3), int64(9), object(6)
memory usage: 4.2+ MB

In [25]:
df_CO_arrestee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88639 entries, 0 to 88638
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   data_year                  88639 non-null  int64
 1   arrestee_id                88639 non-null  int64
 2   incident_id                88639 non-null  int64
 3   arrestee_seq_num           88639 non-null  int64
 4   arrest_date                88639 non-null  object
 5   arrest_type_id             88639 non-null  int64
 6   multiple_indicator         88639 non-null  object
 7   offense_code               88639 non-null  object
 8   age_id                     88639 non-null  int64
 9   age_num                    88639 non-null  int64
 10  sex_code                   88639 non-null  object
 11  race_id                    88639 non-null  int64
 12  ethnicity_id               88639 non-null  int64
 13  resident_code              87313 non-null  object
 14  under_18_disposition_code  8380 non-null   object
 15  clearance_ind              0 non-null      float64
 16  age_range_low_num          88639 non-null  int64
 17  age_range_high_num         3 non-null      float64
dtypes: float64(2), int64(10), object(6)
memory usage: 12.2+ MB

In [26]:
bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

labels = ['0-9', '10-19', '20-29', '30-39','40-49', '50-59', '60-69', '70-79', '80-89', '90-99']

df_NM_arrestee['AgeGroup'] = pd.cut(df_NM_arrestee['age_num'], bins=bins, labels=labels, right=False, ordered=True)

df_NM_arrestee['AgeGroup'].value_counts()

AgeGroup
30-39    10342
20-29     7835
40-49     6084
10-19     2784
50-59     2369
60-69      982
70-79      154
80-89       29
0-9         17
90-99        2
Name: count, dtype: int64

In [27]:
df_CO_arrestee['AgeGroup'] = pd.cut(df_CO_arrestee['age_num'], bins=bins, labels=labels, right=False, ordered=True)

df_CO_arrestee['AgeGroup'].value_counts()

AgeGroup
30-39    28504
20-29    21408
40-49    16425
10-19    11797
50-59     7029
60-69     2912
70-79      482
80-89       75
90-99        6
0-9          1
Name: count, dtype: int64

In [28]:
df_NM_arrestee['ethnicity_id'].value_counts()

ethnicity_id
10    14226
20    11116
40     4484
50      772
Name: count, dtype: int64

In [29]:
df_CO_arrestee['ethnicity_id'].value_counts()

ethnicity_id
20    52107
10    27890
40     8074
50      568
Name: count, dtype: int64

In [ ]:
df_CO_arrestee['offense_code'].value_counts()

offense_code
13B    15080
35A    12436
23C    11555
13A     7303
35B     6373
290     4911
90Z     4721
23H     4157
240     3060
220     2950
520     2669
13C     2005
90J     1251
120     1075
90F     1049
280      972
23D      757
90D      737
100      702
90C      694
26C      416
23F      414
720      372
200      326
250      305
26F      293
40A      273
26A      250
11A      233
11D      212
09A      204
90G      164
370      160
23G      102
26B       84
40B       44
270       40
210       39
36B       31
23E       30
510       29
11C       27
90B       25
09B       22
11B       21
36A       14
23A       14
23B       11
26G        9
26E        6
64A        5
40C        4
39B        3
Name: count, dtype: int64

In [30]:
df_NM_arrestee['offense_code'].value_counts()

offense_code
13B    10801
35A     4828
23C     3696
13A     2945
290     1532
280     1014
35B      888
220      837
520      779
90Z      440
13C      436
23H      386
240      318
100      201
120      196
23F      160
26A      132
90C      128
270       87
23D       87
90D       77
90J       77
26C       51
200       46
11D       44
09A       43
250       41
40C       41
90F       33
11A       33
90K       32
26B       30
90G       26
370       24
720       22
23G       20
40A       13
26F       10
09B       10
510        9
11C        4
11B        3
36B        3
90B        3
23A        2
210        2
40B        2
61A        2
23E        2
64B        1
64A        1
Name: count, dtype: int64

In [31]:
offenses_map = df_CO_offense_type.set_index('offense_code')['offense_name']

df_CO_arrestee['offense_name'] = df_CO_arrestee['offense_code'].map(offenses_map)

df_CO_arrestee.head()

,data_year,arrestee_id,incident_id,arrestee_seq_num,arrest_date,arrest_type_id,multiple_indicator,offense_code,age_id,age_num,sex_code,race_id,ethnicity_id,resident_code,under_18_disposition_code,clearance_ind,age_range_low_num,age_range_high_num,AgeGroup,offense_name
0,2024,60255601,197328785,1,1/3/2024,3,C,90F,26,23,M,10,10,R,NaN,NaN,23,NaN,20-29,"Family Offenses, Nonviolent"
1,2024,57502324,188853124,1,1/3/2024,3,C,13B,28,25,M,10,10,R,NaN,NaN,25,NaN,20-29,Simple Assault
2,2024,56479851,185588235,1,1/8/2024,3,C,280,25,22,M,10,10,N,NaN,NaN,22,NaN,20-29,Stolen Property Offenses
3,2024,56479857,185588257,1,1/9/2024,3,C,13B,69,66,F,10,10,N,NaN,NaN,66,NaN,60-69,Simple Assault
4,2024,56479860,185588268,1,1/11/2024,2,C,13B,26,23,M,10,20,N,NaN,NaN,23,NaN,20-29,Simple Assault

In [32]:
df_NM_arrestee['offense_name'] = df_NM_arrestee['offense_code'].map(offenses_map)

df_NM_arrestee.head()

,data_year,arrestee_id,incident_id,arrestee_seq_num,arrest_date,arrest_type_id,multiple_indicator,offense_code,age_id,age_num,sex_code,race_id,ethnicity_id,resident_code,under_18_disposition_code,clearance_ind,age_range_low_num,age_range_high_num,AgeGroup,offense_name
0,2024,56333576,185132381,1,2024-01-01,2,N,23C,27,24,M,10,10,R,NaN,NaN,24.0,NaN,20-29,Shoplifting
1,2024,56333577,185132385,1,2024-01-01,3,N,35B,33,30,F,10,10,R,NaN,NaN,30.0,NaN,30-39,Drug Equipment Violations
2,2024,56333578,185132391,1,2024-01-02,2,N,290,28,25,F,10,10,R,NaN,NaN,25.0,NaN,20-29,Destruction/Damage/Vandalism of Property
3,2024,56333579,185132397,1,2024-01-02,3,N,13B,55,52,M,10,20,R,NaN,NaN,52.0,NaN,50-59,Simple Assault
4,2024,56333580,185132401,1,2024-01-02,3,N,280,46,43,M,10,10,R,NaN,NaN,43.0,NaN,40-49,Stolen Property Offenses

In [33]:
df_CO_arrestee['offense_name'].value_counts()

offense_name
Simple Assault                                 15080
Drug/Narcotic Violations                       12436
Shoplifting                                    11555
Aggravated Assault                              7303
Drug Equipment Violations                       6373
Destruction/Damage/Vandalism of Property        4911
All Other Offenses                              4721
All Other Larceny                               4157
Motor Vehicle Theft                             3060
Burglary/Breaking & Entering                    2950
Weapon Law Violations                           2669
Intimidation                                    2005
Trespass of Real Property                       1251
Robbery                                         1075
Family Offenses, Nonviolent                     1049
Stolen Property Offenses                         972
Theft From Building                              757
Driving Under the Influence                      737
Kidnapping/Abduction                             702
Disorderly Conduct                               694
Impersonation                                    416
Theft From Motor Vehicle                         414
Animal Cruelty                                   372
Arson                                            326
Counterfeiting/Forgery                           305
Identity Theft                                   293
Prostitution                                     273
False Pretenses/Swindle/Confidence Game          250
Rape                                             233
Criminal Sexual Contact                          212
Murder and Nonnegligent Manslaughter             204
Liquor Law Violations                            164
Pornography/Obscene Material                     160
Theft of Motor Vehicle Parts or Accessories      102
Credit Card/Automated Teller Machine Fraud        84
Assisting or Promoting Prostitution               44
Embezzlement                                      40
Extortion/Blackmail                               39
Statutory Rape                                    31
Theft From Coin-Operated Machine or Device        30
Bribery                                           29
Sexual Assault With An Object                     27
Curfew/Loitering/Vagrancy Violations              25
Negligent Manslaughter                            22
Sodomy                                            21
Incest                                            14
Pocket-picking                                    14
Purse-snatching                                   11
Hacking/Computer Invasion                          9
Wire Fraud                                         6
Human Trafficking, Commercial Sex Acts             5
Purchasing Prostitution                            4
Operating/Promoting/Assisting Gambling             3
Name: count, dtype: int64

In [35]:
df_NM_arrestee['offense_name'].value_counts()

offense_name
Simple Assault                                 10801
Drug/Narcotic Violations                        4828
Shoplifting                                     3696
Aggravated Assault                              2945
Destruction/Damage/Vandalism of Property        1532
Stolen Property Offenses                        1014
Drug Equipment Violations                        888
Burglary/Breaking & Entering                     837
Weapon Law Violations                            779
All Other Offenses                               440
Intimidation                                     436
All Other Larceny                                386
Motor Vehicle Theft                              318
Kidnapping/Abduction                             201
Robbery                                          196
Theft From Motor Vehicle                         160
False Pretenses/Swindle/Confidence Game          132
Disorderly Conduct                               128
Embezzlement                                      87
Theft From Building                               87
Driving Under the Influence                       77
Trespass of Real Property                         77
Impersonation                                     51
Arson                                             46
Criminal Sexual Contact                           44
Murder and Nonnegligent Manslaughter              43
Counterfeiting/Forgery                            41
Purchasing Prostitution                           41
Family Offenses, Nonviolent                       33
Rape                                              33
Failure to Appear                                 32
Credit Card/Automated Teller Machine Fraud        30
Liquor Law Violations                             26
Pornography/Obscene Material                      24
Animal Cruelty                                    22
Theft of Motor Vehicle Parts or Accessories       20
Prostitution                                      13
Identity Theft                                    10
Negligent Manslaughter                            10
Bribery                                            9
Sexual Assault With An Object                      4
Sodomy                                             3
Statutory Rape                                     3
Curfew/Loitering/Vagrancy Violations               3
Pocket-picking                                     2
Extortion/Blackmail                                2
Assisting or Promoting Prostitution                2
Federal Liquor Offenses                            2
Theft From Coin-Operated Machine or Device         2
Human Trafficking, Involuntary Servitude           1
Human Trafficking, Commercial Sex Acts             1
Name: count, dtype: int64